TelepotCoolDownSeconds: 5
AmountOfPlayersToTeleportEachTime: 5
Debug: false
ConfigVersion: 1

Messages:
  NoPermission: "&8(&6&lO&r&8-&e&lTeleport&r&8) &fSorry, but you do not have permission to do this!"
  TeleportAlreadyInProgress: "&8(&6&lO&r&8-&e&lTeleport&r&8) &fA &eTeleport All &fis already in progress!"
  FinishedTeleporting: "&8(&6&lO&r&8-&e&lTeleport&r&8) &fTelepot All has finished.."
  Broadcast: "&8(&6&lO&r&8-&e&lTeleport&r&8) &fStarting Teleport All.."
