name: Optimized_Teleportation
version: ${project.version}
main: me.great_array.optimized_teleportation.Teleport
api-version: 1.16
authors: [ Great_Array ]
description: A plugin that lets you teleport a lot of players to you without causing server lag or crashes! This is only useful for servers with a larger player base (25+ Players, you can use it anywhere tho!)

commands:
  tpe:
    description: Teleports all players to the location of where you executed the command
    aliases:
      - otpa
      - optimizedtpa